require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/clubs", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Club. As you add validations to Club, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Club.create! valid_attributes
      get clubs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      club = Club.create! valid_attributes
      get club_url(club)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_club_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      club = Club.create! valid_attributes
      get edit_club_url(club)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Club" do
        expect {
          post clubs_url, params: { club: valid_attributes }
        }.to change(Club, :count).by(1)
      end

      it "redirects to the created club" do
        post clubs_url, params: { club: valid_attributes }
        expect(response).to redirect_to(club_url(Club.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Club" do
        expect {
          post clubs_url, params: { club: invalid_attributes }
        }.to change(Club, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post clubs_url, params: { club: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested club" do
        club = Club.create! valid_attributes
        patch club_url(club), params: { club: new_attributes }
        club.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the club" do
        club = Club.create! valid_attributes
        patch club_url(club), params: { club: new_attributes }
        club.reload
        expect(response).to redirect_to(club_url(club))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        club = Club.create! valid_attributes
        patch club_url(club), params: { club: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested club" do
      club = Club.create! valid_attributes
      expect {
        delete club_url(club)
      }.to change(Club, :count).by(-1)
    end

    it "redirects to the clubs list" do
      club = Club.create! valid_attributes
      delete club_url(club)
      expect(response).to redirect_to(clubs_url)
    end
  end
end
